# Generated by Django 4.2.6 on 2023-10-24 12:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("todos", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="todo",
            name="fineshed_at",
            field=models.DateField(null=True),
        ),
    ]
